---@meta edgetx

--- AUTO-GENERATED BY edgetx-lua-gen (https://github.com/JeffreyChix/edgetx-lua-gen) — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- All EdgeTX constants (191 total)

-- ── general constants ───────────────────────────────────────────

---@type integer
TINSIZE = 0

--- shadow font    Only color displays
---@type integer
SHADOWED = 0

---@type integer
COLOR = 0

---@type integer
BOOL = 0

---@type integer
STRING = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
TEXT_COLOR = 0

--- → COLOR_THEME_SECONDARY3
---@type integer
TEXT_BGCOLOR = 0

--- → COLOR_THEME_PRIMARY2
---@type integer
TEXT_INVERTED_COLOR = 0

--- → COLOR_THEME_FOCUS
---@type integer
TEXT_INVERTED_BGCOLOR = 0

--- → COLOR_THEME_PRIMARY3
---@type integer
LINE_COLOR = 0

--- → COLOR_THEME_SECONDARY3
---@type integer
SCROLLBOX_COLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
MENU_TITLE_BGCOLOR = 0

--- → COLOR_THEME_PRIMARY2
---@type integer
MENU_TITLE_COLOR = 0

--- → COLOR_THEME_PRIMARY3
---@type integer
MENU_TITLE_DISABLE_COLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
HEADER_COLOR = 0

--- → COLOR_THEME_WARNING
---@type integer
ALARM_COLOR = 0

--- → COLOR_THEME_WARNING
---@type integer
WARNING_COLOR = 0

--- → COLOR_THEME_DISABLED
---@type integer
TEXT_DISABLE_COLOR = 0

--- → COLOR_THEME_SECONDARY2
---@type integer
CURVE_AXIS_COLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
CURVE_COLOR = 0

--- → COLOR_THEME_WARNING
---@type integer
CURVE_CURSOR_COLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
TITLE_BGCOLOR = 0

--- → COLOR_THEME_FOCUS
---@type integer
TRIM_BGCOLOR = 0

--- → COLOR_THEME_PRIMARY1
---@type integer
TRIM_SHADOW_COLOR = 0

--- → COLOR_THEME_FOCUS
---@type integer
HEADER_BGCOLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
HEADER_ICON_BGCOLOR = 0

--- → COLOR_THEME_FOCUS
---@type integer
HEADER_CURRENT_BGCOLOR = 0

--- → COLOR_THEME_PRIMARY2
---@type integer
MAINVIEW_PANES_COLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
MAINVIEW_GRAPHICS_COLOR = 0

--- → COLOR_THEME_PRIMARY1
---@type integer
OVERLAY_COLOR = 0

--- → COLOR_THEME_SECONDARY1
---@type integer
BARGRAPH1_COLOR = 0

--- → COLOR_THEME_SECONDARY2
---@type integer
BARGRAPH2_COLOR = 0

--- → COLOR_THEME_SECONDARY3
---@type integer
BARGRAPH_BGCOLOR = 0

--- These are the theme colors plus , and they can be changed with the function lcd.setColor\(color_index, color\). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
CUSTOM_COLOR = 0

---@type integer
MENU_HEADER_HEIGHT = 0

--- WHITE | RGB: rgb(255, 255, 255) | Is Light: true | Is Dark: false
---@type integer
WHITE = 0

--- GREY | RGB: rgb(128, 128, 128) | Is Light: true | Is Dark: false
---@type integer
GREY = 0

--- DARKGREY | RGB: rgb(169, 169, 169) | Is Light: true | Is Dark: false
---@type integer
DARKGREY = 0

--- BLACK | RGB: rgb(0, 0, 0) | Is Light: false | Is Dark: true
---@type integer
BLACK = 0

--- YELLOW | RGB: rgb(255, 255, 0) | Is Light: true | Is Dark: false
---@type integer
YELLOW = 0

--- BLUE | RGB: rgb(0, 0, 255) | Is Light: false | Is Dark: true
---@type integer
BLUE = 0

--- LIGHTGREY | RGB: rgb(211, 211, 211) | Is Light: true | Is Dark: false
---@type integer
LIGHTGREY = 0

---@type integer
RED = 0

--- DARKRED | RGB: rgb(139, 0, 0) | Is Light: false | Is Dark: true
---@type integer
DARKRED = 0

---@type integer
FIXEDWIDTH = 0

---@type integer
FILL_WHITE = 0

--- grey fill
---@type integer
GREY_DEFAULT = 0

---@type integer
FULLSCALE = 0

--- jumbo font  2.0.6
---@type integer
XXLSIZE = 0

--- double size font
---@type integer
DBLSIZE = 0

--- mid sized font
---@type integer
MIDSIZE = 0

--- small font
---@type integer
SMLSIZE = 0

--- inverted display
---@type integer
INVERS = 0

--- bold font    Only color displays. This is a font size on its own - cannot be combined with other font size flags.
---@type integer
BOLD = 0

--- blinking text
---@type integer
BLINK = 0

--- right justify
---@type integer
RIGHT = 0

--- left justify  2.0.6  Default for most functions not related to bitmaps
---@type integer
LEFT = 0

--- center justify    Only color displays
---@type integer
CENTER = 0

--- single decimal place
---@type integer
PREC1 = 0

--- two decimal places
---@type integer
PREC2 = 0

---@type integer
VALUE = 0

---@type integer
SOURCE = 0

---@type integer
REPLACE = 0

---@type integer
MIXSRC_MAX = 0

---@type integer
MIXSRC_FIRST_INPUT = 0

---@type integer
MIXSRC_SA = 0

---@type integer
MIXSRC_SB = 0

---@type integer
MIXSRC_SC = 0

---@type integer
MIXSRC_SD = 0

---@type integer
MIXSRC_SE = 0

---@type integer
MIXSRC_SG = 0

---@type integer
MIXSRC_SF = 0

---@type integer
MIXSRC_SH = 0

---@type integer
MIXSRC_CH1 = 0

---@type integer
SWSRC_LAST = 0

---@type integer
MAX_SENSORS = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREV = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_NEXT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_DEC = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_INC = 0

---@type integer
ROTENC_LOWSPEED = 0

---@type integer
ROTENC_MIDSPEED = 0

---@type integer
ROTENC_HIGHSPEED = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREV_REPT = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_NEXT_REPT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_DEC_REPT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_INC_REPT = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_PREV_PAGE = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_NEXT_PAGE = 0

---@type integer
EVT_VIRTUAL_MENU = 0

---@type integer
EVT_VIRTUAL_MENU_LONG = 0

---@type integer
EVT_VIRTUAL_ENTER = 0

---@type integer
EVT_VIRTUAL_ENTER_LONG = 0

---@type integer
EVT_VIRTUAL_EXIT = 0

--- EXIT key release
---@type integer
EVT_EXIT_BREAK = 0

---@type integer
EVT_RTN_FIRST = 0

--- rotary encoder rotated left
---@type integer
EVT_ROT_LEFT = 0

--- rotary encoder rotated right
---@type integer
EVT_ROT_RIGHT = 0

--- pixels will be black
---@type integer
FORCE = 0

--- pixels will be white
---@type integer
ERASE = 0

---@type integer
ROUND = 0

---@type integer
SOLID = 0

--- lines will appear dotted
---@type integer
DOTTED = 0

--- width in pixels
---@type integer
LCD_W = 0

--- height in pixels
---@type integer
LCD_H = 0

---@type integer
PLAY_NOW = 0

---@type integer
PLAY_BACKGROUND = 0

--- display hours    Only for drawTimer
---@type integer
TIMEHOUR = 0

---@type integer
UNIT_RAW = 0

---@type integer
UNIT_VOLTS = 0

---@type integer
UNIT_AMPS = 0

---@type integer
UNIT_MILLIAMPS = 0

---@type integer
UNIT_KTS = 0

---@type integer
UNIT_METERS_PER_SECOND = 0

---@type integer
UNIT_FEET_PER_SECOND = 0

---@type integer
UNIT_KMH = 0

---@type integer
UNIT_MPH = 0

---@type integer
UNIT_METERS = 0

---@type integer
UNIT_KM = 0

---@type integer
UNIT_FEET = 0

---@type integer
UNIT_CELSIUS = 0

---@type integer
UNIT_FAHRENHEIT = 0

---@type integer
UNIT_PERCENT = 0

---@type integer
UNIT_MAH = 0

---@type integer
UNIT_WATTS = 0

---@type integer
UNIT_MILLIWATTS = 0

---@type integer
UNIT_DB = 0

---@type integer
UNIT_RPMS = 0

---@type integer
UNIT_G = 0

---@type integer
UNIT_DEGREE = 0

---@type integer
UNIT_RADIANS = 0

---@type integer
UNIT_MILLILITERS = 0

---@type integer
UNIT_FLOZ = 0

---@type integer
UNIT_MILLILITERS_PER_MINUTE = 0

---@type integer
UNIT_HERTZ = 0

---@type integer
UNIT_MS = 0

---@type integer
UNIT_US = 0

---@type integer
UNIT_HOURS = 0

---@type integer
UNIT_MINUTES = 0

---@type integer
UNIT_SECONDS = 0

---@type integer
UNIT_CELLS = 0

---@type integer
UNIT_DATETIME = 0

---@type integer
UNIT_GPS = 0

---@type integer
UNIT_BITFIELD = 0

---@type integer
UNIT_TEXT = 0

---@type integer
BATTERY_CHARGE_COLOR = 0

---@type integer
CHECKBOX_COLOR = 0

---@type integer
DEFAULT_BGCOLOR = 0

---@type integer
DEFAULT_COLOR = 0

---@type integer
DISABLE_COLOR = 0

---@type integer
FOCUS_BGCOLOR = 0

---@type integer
FOCUS_COLOR = 0

---@type integer
HIGHLIGHT_COLOR = 0

---@type integer
MENU_BGCOLOR = 0

---@type integer
MENU_COLOR = 0

---@type integer
MENU_HIGHLIGHT_BGCOLOR = 0

---@type integer
MENU_HIGHLIGHT_COLOR = 0

---@type integer
MENU_LINE_COLOR = 0

---@type integer
SCROLLBAR_COLOR = 0

---@type integer
TABLE_BGCOLOR = 0

---@type integer
TABLE_HEADER_BGCOLOR = 0

---@type integer
TEXT_STATUSBAR_COLOR = 0

--- center vertically  2.5.0  Only color displays
---@type integer
VCENTER = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_PRIMARY1 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_PRIMARY2 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_PRIMARY3 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_SECONDARY1 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_SECONDARY2 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_SECONDARY3 = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_FOCUS = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_EDIT = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_ACTIVE = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_WARNING = 0

--- Theme color. They can be changed with the function lcd.setColor(color_index, color). Please note: if an indexed color is changed, then it changes everywhere that it is used. For the theme colors, this is not only in other widgets, but everywhere throughout the radio's user interface!
---@type integer
COLOR_THEME_DISABLED = 0

---@type integer
LIGHTWHITE = 0

--- DARKBLUE | RGB: rgb(0, 0, 139) | Is Light: false | Is Dark: true
---@type integer
DARKBLUE = 0

--- GREEN | RGB: rgb(0, 128, 0) | Is Light: false | Is Dark: true
---@type integer
GREEN = 0

--- DARKGREEN | RGB: rgb(0, 100, 0) | Is Light: false | Is Dark: true
---@type integer
DARKGREEN = 0

---@type integer
LIGHTBROWN = 0

---@type integer
DARKBROWN = 0

---@type integer
BRIGHTGREEN = 0

--- ORANGE | RGB: rgb(255, 165, 0) | Is Light: true | Is Dark: false
---@type integer
ORANGE = 0

--- When the finger touches down on the screen
---@type integer
EVT_TOUCH_FIRST = 0

--- If the finger leaves the screen without tap or slide
---@type integer
EVT_TOUCH_BREAK = 0

--- Repeats while the finger is sliding on the screen
---@type integer
EVT_TOUCH_SLIDE = 0

--- If the finger leaves the screen after a quick tap
---@type integer
EVT_TOUCH_TAP = 0

---@type integer
AM_RDO = 0

---@type integer
AM_HID = 0

---@type integer
AM_SYS = 0

---@type integer
AM_DIR = 0

---@type integer
AM_ARC = 0

