---@meta edgetx

--- AUTO-GENERATED BY edgetx-lua-gen (https://github.com/JeffreyChix/edgetx-lua-gen) — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- All EdgeTX constants (221 total)

-- ── general constants ───────────────────────────────────────────

---@type integer
EVT_PAGE_FIRST = 0

--- MENU key long press
---@type integer
EVT_PAGE_LONG = 0

---@type integer
EVT_PAGE_REPT = 0

--- PAGE key release
---@type integer
EVT_PAGE_BREAK = 0

---@type integer
EVT_MENU_FIRST = 0

---@type integer
EVT_MENU_LONG = 0

---@type integer
EVT_MENU_REPT = 0

--- MENU key release
---@type integer
EVT_MENU_BREAK = 0

---@type integer
EVT_ENTER_FIRST = 0

--- ENT key long press
---@type integer
EVT_ENTER_LONG = 0

---@type integer
EVT_ENTER_REPT = 0

--- ENT key release
---@type integer
EVT_ENTER_BREAK = 0

---@type integer
EVT_EXIT_FIRST = 0

---@type integer
EVT_EXIT_LONG = 0

---@type integer
EVT_EXIT_REPT = 0

--- EXIT key release
---@type integer
EVT_EXIT_BREAK = 0

--- + key press
---@type integer
EVT_PLUS_FIRST = 0

---@type integer
EVT_PLUS_LONG = 0

--- + key repeat
---@type integer
EVT_PLUS_REPT = 0

--- + key release
---@type integer
EVT_PLUS_BREAK = 0

--- - key press
---@type integer
EVT_MINUS_FIRST = 0

---@type integer
EVT_MINUS_LONG = 0

--- - key repeat
---@type integer
EVT_MINUS_REPT = 0

--- - key release
---@type integer
EVT_MINUS_BREAK = 0

--- rotary encoder rotated left
---@type integer
EVT_ROT_LEFT = 0

--- rotary encoder rotated right
---@type integer
EVT_ROT_RIGHT = 0

---@type integer
EVT_UP_FIRST = 0

---@type integer
EVT_UP_LONG = 0

---@type integer
EVT_UP_REPT = 0

---@type integer
EVT_UP_BREAK = 0

---@type integer
EVT_DOWN_FIRST = 0

---@type integer
EVT_DOWN_LONG = 0

---@type integer
EVT_DOWN_REPT = 0

---@type integer
EVT_DOWN_BREAK = 0

---@type integer
EVT_RIGHT_FIRST = 0

---@type integer
EVT_RIGHT_LONG = 0

---@type integer
EVT_RIGHT_REPT = 0

---@type integer
EVT_RIGHT_BREAK = 0

---@type integer
EVT_LEFT_FIRST = 0

---@type integer
EVT_LEFT_LONG = 0

---@type integer
EVT_LEFT_REPT = 0

---@type integer
EVT_LEFT_BREAK = 0

---@type integer
EVT_SHIFT_FIRST = 0

---@type integer
EVT_SHIFT_LONG = 0

---@type integer
EVT_SHIFT_REPT = 0

---@type integer
EVT_SHIFT_BREAK = 0

---@type integer
EVT_PAGEUP_FIRST = 0

---@type integer
EVT_PAGEUP_LONG = 0

---@type integer
EVT_PAGEUP_REPT = 0

---@type integer
EVT_PAGEUP_BREAK = 0

---@type integer
EVT_PAGEDN_FIRST = 0

---@type integer
EVT_PAGEDN_LONG = 0

---@type integer
EVT_PAGEDN_REPT = 0

---@type integer
EVT_PAGEDN_BREAK = 0

---@type integer
EVT_SYS_FIRST = 0

---@type integer
EVT_SYS_LONG = 0

---@type integer
EVT_SYS_REPT = 0

---@type integer
EVT_SYS_BREAK = 0

---@type integer
EVT_MODEL_FIRST = 0

---@type integer
EVT_MODEL_LONG = 0

---@type integer
EVT_MODEL_REPT = 0

---@type integer
EVT_MODEL_BREAK = 0

---@type integer
EVT_TELEM_FIRST = 0

---@type integer
EVT_TELEM_LONG = 0

---@type integer
EVT_TELEM_REPT = 0

---@type integer
EVT_TELEM_BREAK = 0

---@type integer
EVT_TOUCH_FIRST = 0

---@type integer
EVT_TOUCH_BREAK = 0

---@type integer
EVT_TOUCH_SLIDE = 0

---@type integer
EVT_TOUCH_TAP = 0

---@type integer
TINSIZE = 0

---@type integer
SHADOWED = 0

---@type integer
COLOR = 0

---@type integer
BOOL = 0

---@type integer
STRING = 0

---@type integer
TEXT_COLOR = 0

---@type integer
TEXT_BGCOLOR = 0

---@type integer
TEXT_INVERTED_COLOR = 0

---@type integer
TEXT_INVERTED_BGCOLOR = 0

---@type integer
LINE_COLOR = 0

---@type integer
SCROLLBOX_COLOR = 0

---@type integer
MENU_TITLE_BGCOLOR = 0

---@type integer
MENU_TITLE_COLOR = 0

---@type integer
MENU_TITLE_DISABLE_COLOR = 0

---@type integer
HEADER_COLOR = 0

---@type integer
ALARM_COLOR = 0

---@type integer
WARNING_COLOR = 0

---@type integer
TEXT_DISABLE_COLOR = 0

---@type integer
CURVE_AXIS_COLOR = 0

---@type integer
CURVE_COLOR = 0

---@type integer
CURVE_CURSOR_COLOR = 0

---@type integer
TITLE_BGCOLOR = 0

---@type integer
TRIM_BGCOLOR = 0

---@type integer
TRIM_SHADOW_COLOR = 0

---@type integer
HEADER_BGCOLOR = 0

---@type integer
HEADER_ICON_BGCOLOR = 0

---@type integer
HEADER_CURRENT_BGCOLOR = 0

---@type integer
MAINVIEW_PANES_COLOR = 0

---@type integer
MAINVIEW_GRAPHICS_COLOR = 0

---@type integer
OVERLAY_COLOR = 0

---@type integer
BARGRAPH1_COLOR = 0

---@type integer
BARGRAPH2_COLOR = 0

---@type integer
BARGRAPH_BGCOLOR = 0

---@type integer
CUSTOM_COLOR = 0

---@type integer
MENU_HEADER_HEIGHT = 0

---@type integer
WHITE = 0

---@type integer
GREY = 0

---@type integer
DARKGREY = 0

---@type integer
BLACK = 0

---@type integer
YELLOW = 0

---@type integer
BLUE = 0

---@type integer
LIGHTGREY = 0

---@type integer
RED = 0

---@type integer
DARKRED = 0

---@type integer
FIXEDWIDTH = 0

---@type integer
FILL_WHITE = 0

---@type integer
GREY_DEFAULT = 0

---@type integer
FULLSCALE = 0

---@type integer
XXLSIZE = 0

---@type integer
DBLSIZE = 0

---@type integer
MIDSIZE = 0

---@type integer
SMLSIZE = 0

---@type integer
INVERS = 0

---@type integer
BOLD = 0

---@type integer
BLINK = 0

---@type integer
RIGHT = 0

---@type integer
LEFT = 0

---@type integer
CENTER = 0

---@type integer
PREC1 = 0

---@type integer
PREC2 = 0

---@type integer
VALUE = 0

---@type integer
SOURCE = 0

---@type integer
REPLACE = 0

---@type integer
MIXSRC_MAX = 0

---@type integer
MIXSRC_FIRST_INPUT = 0

---@type integer
MIXSRC_SA = 0

---@type integer
MIXSRC_SB = 0

---@type integer
MIXSRC_SC = 0

---@type integer
MIXSRC_SD = 0

---@type integer
MIXSRC_SE = 0

---@type integer
MIXSRC_SG = 0

---@type integer
MIXSRC_SF = 0

---@type integer
MIXSRC_SH = 0

---@type integer
MIXSRC_CH1 = 0

---@type integer
SWSRC_LAST = 0

---@type integer
MAX_SENSORS = 0

---@type integer
EVT_VIRTUAL_PREV = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_NEXT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_DEC = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_INC = 0

---@type integer
ROTENC_LOWSPEED = 0

---@type integer
ROTENC_MIDSPEED = 0

---@type integer
ROTENC_HIGHSPEED = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREV_REPT = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_NEXT_REPT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_DEC_REPT = 0

--- for VALUES navigation
---@type integer
EVT_VIRTUAL_INC_REPT = 0

---@type integer
EVT_VIRTUAL_PREV_PAGE = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_NEXT_PAGE = 0

---@type integer
EVT_VIRTUAL_MENU = 0

---@type integer
EVT_VIRTUAL_MENU_LONG = 0

---@type integer
EVT_VIRTUAL_ENTER = 0

---@type integer
EVT_VIRTUAL_ENTER_LONG = 0

---@type integer
EVT_VIRTUAL_EXIT = 0

---@type integer
EVT_RTN_FIRST = 0

---@type integer
FORCE = 0

---@type integer
ERASE = 0

---@type integer
ROUND = 0

---@type integer
SOLID = 0

---@type integer
DOTTED = 0

---@type integer
LCD_W = 0

---@type integer
LCD_H = 0

---@type integer
PLAY_NOW = 0

---@type integer
PLAY_BACKGROUND = 0

---@type integer
TIMEHOUR = 0

---@type integer
UNIT_RAW = 0

---@type integer
UNIT_VOLTS = 0

---@type integer
UNIT_AMPS = 0

---@type integer
UNIT_MILLIAMPS = 0

---@type integer
UNIT_KTS = 0

---@type integer
UNIT_METERS_PER_SECOND = 0

---@type integer
UNIT_FEET_PER_SECOND = 0

---@type integer
UNIT_KMH = 0

---@type integer
UNIT_MPH = 0

---@type integer
UNIT_METERS = 0

---@type integer
UNIT_KM = 0

---@type integer
UNIT_FEET = 0

---@type integer
UNIT_CELSIUS = 0

---@type integer
UNIT_FAHRENHEIT = 0

---@type integer
UNIT_PERCENT = 0

---@type integer
UNIT_MAH = 0

---@type integer
UNIT_WATTS = 0

---@type integer
UNIT_MILLIWATTS = 0

---@type integer
UNIT_DB = 0

---@type integer
UNIT_RPMS = 0

---@type integer
UNIT_G = 0

---@type integer
UNIT_DEGREE = 0

---@type integer
UNIT_RADIANS = 0

---@type integer
UNIT_MILLILITERS = 0

---@type integer
UNIT_FLOZ = 0

---@type integer
UNIT_MILLILITERS_PER_MINUTE = 0

---@type integer
UNIT_HERTZ = 0

---@type integer
UNIT_MS = 0

---@type integer
UNIT_US = 0

---@type integer
UNIT_HOURS = 0

---@type integer
UNIT_MINUTES = 0

---@type integer
UNIT_SECONDS = 0

---@type integer
UNIT_CELLS = 0

---@type integer
UNIT_DATETIME = 0

---@type integer
UNIT_GPS = 0

---@type integer
UNIT_BITFIELD = 0

---@type integer
UNIT_TEXT = 0

--- when a key is pressed a `` event is generated
---@type integer
FIRST = 0

--- if the key continues to be pressed, then after a while a `` event is generated
---@type integer
LONG = 0

--- if the key continues to be pressed, then a `` events are being generated
---@type integer
REPEAT = 0

--- when the key is released a `` event is generated
---@type integer
BREAK = 0

--- rotary encoder release
---@type integer
EVT_ROT_BREAK = 0

--- rotary encoder long press
---@type integer
EVT_ROT_LONG = 0

--- Given the large number of radios supported by OpenTX, and the large difference in keys available on those, a set of  KEYS has been defined and are mapped to best fit available hardware
---@type integer
VIRTUAL = 0

--- for PAGE navigation
---@type integer
EVT_VIRTUAL_PREVIOUS_PAGE = 0

--- for FIELDS navigation
---@type integer
EVT_VIRTUAL_PREVIOUS = 0

