---@meta edgetx

--- AUTO-GENERATED BY edgetx-lua-gen (https://github.com/JeffreyChix/edgetx-lua-gen) — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- lcd.* LCD drawing functions

---@class (exact) lcdLib
lcd = {}

--- Refresh the LCD screen
---
--- **Since:** 2.2.0
--- > **Notice:** This function only works in stand-alone and telemetry scripts.
function lcd.refresh() end
--- Clear the LCD screen
---
--- **Since:** 2.0.0
--- > **Notice:** This function only works in stand-alone and telemetry scripts.
---@param color? number (optional, only on color screens)
function lcd.clear(color) end
--- Reset the backlight timeout
---
--- **Since:** 2.3.6
function lcd.resetBacklightTimeout() end
--- Draw a single pixel at (x,y) position
---
--- **Since:** 2.0.0
--- > **Notice:** Taranis has an LCD display width of 212 pixels and height of 64 pixels.
--- > Position (0,0) is at top left. Y axis is negative, top line is 0,
--- > bottom line is 63. Drawing on an existing black pixel produces white pixel (TODO check this!)
---@param x number (positive number) x position
---@param y number (positive number) y position
---@param flags? number (optional) lcdflags
function lcd.drawPoint(x, y, flags) end
--- Draw a straight line on LCD
---
--- **Since:** 2.0.0
--- > **Notice:** If the start or the end of the line is outside the LCD dimensions, then the
--- > whole line will not be drawn (starting from OpenTX 2.1.5)
---@param x1 number (positive numbers) starting coordinate
---@param y1 number (positive numbers) starting coordinate
---@param x2 number (positive numbers) end coordinate
---@param y2 number (positive numbers) end coordinate
---@param pattern number SOLID or DOTTED
---@param flags? number lcdflags
function lcd.drawLine(x1, y1, x2, y2, pattern, flags) end
--- Returns the rightmost x position from previous output
---
--- **Since:** 2.0.0
--- > **Notice:** Only available on Taranis
--- > **Notice:** For added clarity, it is recommended to use lcd.getLastRightPos()
---@return number number # (integer) x position
function lcd.getLastPos() end
--- Returns the rightest x position from previous drawtext or drawNumber output
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Taranis
--- > **Notice:** This is strictly equivalent to former lcd.getLastPos()
---@return number number # (integer) x position
function lcd.getLastRightPos() end
--- Returns the leftmost x position from previous drawtext or drawNumber output
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Taranis
---@return number number # (integer) x position
function lcd.getLastLeftPos() end
--- Draw a text beginning at (x,y)
---
--- **Since:** 2.0.0
---@param x number (positive numbers) starting coordinate
---@param y number (positive numbers) starting coordinate
---@param text string (string) text to display
---@param flags? number (unsigned number) drawing flags. All values can be
--- combined together using the + character. ie BLINK + DBLSIZE.
--- See the [Appendix](../appendix/fonts.md) for available characters in each font set.
--- `0 or not specified` normal font
--- `XXLSIZE` jumbo sized font
--- `DBLSIZE` double size font
--- `MIDSIZE` mid sized font
--- `SMLSIZE` small font
--- `INVERS` inverted display
--- `BLINK` blinking text
--- `SHADOWED` Horus only, apply a shadow effect
function lcd.drawText(x, y, text, flags) end
--- Display a value formatted as time at (x,y)
---
--- **Since:** 2.0.0
---@param x number (positive numbers) starting coordinate
---@param y number (positive numbers) starting coordinate
---@param value number (number) time in seconds
---@param flags? number (unsigned number) drawing flags:
--- `0 or not specified` normal representation (minutes and seconds)
--- `TIMEHOUR` display hours
--- other general LCD flag also apply
--- `SHADOWED` Horus only, apply a shadow effect
function lcd.drawTimer(x, y, value, flags) end
--- Display a number at (x,y)
---
--- **Since:** 2.0.0
---@param x number (positive numbers) starting coordinate
---@param y number (positive numbers) starting coordinate
---@param value number (number) value to display
---@param flags? number (unsigned number) drawing flags:
--- `0 or not specified` display with no decimal (like abs())
--- `PREC1` display with one decimal place (number 386 is displayed as 38.6)
--- `PREC2` display with tow decimal places (number 386 is displayed as 3.86)
--- other general LCD flag also apply
--- `SHADOWED` Horus only, apply a shadow effect
function lcd.drawNumber(x, y, value, flags) end
--- Display a telemetry value at (x,y)
---
--- **Since:** 2.0.6
---@param x number (positive numbers) starting coordinate
---@param y number (positive numbers) starting coordinate
---@param source number|string can be a source identifier (number) or a source name (string).
--- See getValue()
---@param flags? number (unsigned number) drawing flags
function lcd.drawChannel(x, y, source, flags) end
--- Draw a text representation of switch at (x,y)
---
--- **Since:** 2.0.0
---@param x number (positive numbers) starting coordinate
---@param y number (positive numbers) starting coordinate
---@param switch number number of switch to display, negative number
--- displays negated switch
---@param flags? number (unsigned number) drawing flags, only SMLSIZE, BLINK and INVERS.
function lcd.drawSwitch(x, y, switch, flags) end
--- Displays the name of the corresponding input as defined by the source at (x,y)
---
--- **Since:** 2.0.0
---@param x number (positive numbers) starting coordinate
---@param y number (positive numbers) starting coordinate
---@param source number source index
---@param flags? number (unsigned number) drawing flags
function lcd.drawSource(x, y, source, flags) end
--- Displays a bitmap at (x,y)
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Horus
---@param bitmap any (pointer) point to a bitmap previously opened with Bitmap.open()
---@param x number (positive numbers) starting coordinates
---@param y number (positive numbers) starting coordinates
---@param scale? number (positive numbers) scale in %, 50 divides size by two, 100 is unchanged, 200 doubles size.
--- Omitting scale draws image in 1:1 scale and is faster than specifying 100 for scale.
function lcd.drawBitmap(bitmap, x, y, scale) end
--- Draw a bitmap at (x,y)
---
--- **Since:** 2.0.0
--- > **Notice:** Maximum image size is [display width / 2] x [display height] pixels.
---@param x number (positive numbers) starting coordinates
---@param y number (positive numbers) starting coordinates
---@param name string (string) full path to the bitmap on SD card (i.e. “/IMAGES/test.bmp”)
function lcd.drawPixmap(x, y, name) end
--- Draw a rectangle from top left corner (x,y) of specified width and height
---
--- **Since:** 2.0.0
---@param x number (positive numbers) top left corner position
---@param y number (positive numbers) top left corner position
---@param w number (number) width in pixels
---@param h number (number) height in pixels
---@param flags? number (unsigned number) drawing flags
---@param t? number thickness in pixels, defaults to 1 (only on Horus)
function lcd.drawRectangle(x, y, w, h, flags, t) end
--- Draw a solid rectangle from top left corner (x,y) of specified width and height
---
--- **Since:** 2.0.0
---@param x number (positive numbers) top left corner position
---@param y number (positive numbers) top left corner position
---@param w number (number) width in pixels
---@param h number (number) height in pixels
---@param flags? number (unsigned number) drawing flags
function lcd.drawFilledRectangle(x, y, w, h, flags) end
--- Draw a simple gauge that is filled based upon fill value
---
--- **Since:** 2.0.0
---@param x number (positive numbers) top left corner position
---@param y number (positive numbers) top left corner position
---@param w number (number) width in pixels
---@param h number (number) height in pixels
---@param fill number amount of fill to apply
---@param maxfill number total value of fill
---@param flags? number (unsigned number) drawing flags
function lcd.drawGauge(x, y, w, h, fill, maxfill, flags) end
--- Draw a title bar
---
--- **Since:** 2.0.0
--- > **Notice:** Only available on Taranis
---@param title string (string) text for the title
---@param page number page number
---@param pages number total number of pages. Only used as indicator on
--- the right side of title bar. (i.e. idx=2, cnt=5, display `2/5`)
function lcd.drawScreenTitle(title, page, pages) end
--- Draw a combo box
---
--- **Since:** 2.0.0
--- > **Notice:** Only available on Taranis
---@param x number (positive numbers) top left corner position
---@param y number (positive numbers) top left corner position
---@param w number (number) width of combo box in pixels
---@param list table combo box elements, each element is a string
---@param idx number (integer) index of entry to highlight
---@param flags? number (unsigned number) drawing flags, the flags can not be combined:
--- `BLINK` combo box is expanded
--- `INVERS` combo box collapsed, text inversed
--- `0 or not present` combo box collapsed, text normal
function lcd.drawCombobox(x, y, w, list, idx, flags) end
--- Set a color for specific area
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Colorlcd radios
---@param area number (unsigned number) specific screen area in the list bellow
--- `TEXT_COLOR`
--- `TEXT_BGCOLOR`
--- `TEXT_INVERTED_COLOR`
--- `TEXT_INVERTED_BGCOLOR`
--- `LINE_COLOR`
--- `SCROLLBOX_COLOR`
--- `MENU_TITLE_BGCOLOR`
--- `MENU_TITLE_COLOR`
--- `MENU_TITLE_DISABLE_COLOR`
--- `HEADER_COLOR`
--- `ALARM_COLOR`
--- `WARNING_COLOR`
--- `TEXT_DISABLE_COLOR`
--- `CURVE_AXIS_COLOR`
--- `CURVE_COLOR`
--- `CURVE_CURSOR_COLOR`
--- `TITLE_BGCOLOR`
--- `TRIM_BGCOLOR`
--- `TRIM_SHADOW_COLOR`
--- `HEADER_BGCOLOR`
--- `HEADER_ICON_BGCOLOR`
--- `HEADER_CURRENT_BGCOLOR`
--- `MAINVIEW_PANES_COLOR`
--- `MAINVIEW_GRAPHICS_COLOR`
--- `OVERLAY_COLOR`
--- `BARGRAPH1_COLOR`
--- `BARGRAPH2_COLOR`
--- `BARGRAPH_BGCOLOR`
--- `CUSTOM_COLOR`
---@param color number (number) color in 5/6/5 rgb format. The following prefined colors are available
--- `WHITE`
--- `GREY`
--- `LIGHTGREY`
--- `DARKGREY`
--- `BLACK`
--- `YELLOW`
--- `BLUE`
--- `RED`
--- `DARKRED`
function lcd.setColor(area, color) end
--- Get the color for specific area : see lcd.setColor for area list
---
--- **Since:** 2.3.11
--- > **Notice:** Only available on Colorlcd radios
---@param area any
function lcd.getColor(area) end
--- Returns a 5/6/5 rgb color code, that can be used with lcd.setColor
---
--- **Since:** 2.2.0
--- > **Notice:** Only available on Colorlcd radios
---@param r number a number between 0x00 and 0xff that expresses te amount of red in the color
---@param g number a number between 0x00 and 0xff that expresses te amount of green in the color
---@param b number a number between 0x00 and 0xff that expresses te amount of blue in the color
---@return number number # (integer) rgb color expressed in 5/6/5 format
function lcd.RGB(r, g, b) end
